name: Publish Gem

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby 3.0.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
      - name: Check release validity
        run: sh .github/scripts/check-release.sh
      - name: Publish to RubyGems
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build chromable.gemspec
          gem push *.gem
        env:
          GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_AUTH_TOKEN}}
